name: mi_card
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/

  fonts:
  - family: Nanum Pen Script
    fonts:
    - asset: fonts/NanumPenScript-Regular.ttf

  - family: Patrick Hand 
    fonts:
    - asset: fonts/PatrickHand-Regular.ttf
